### ISSUE TITLE
mysql connector 5.1.48 throws exception on getConnection()

### ISSUE THREAD

**Issue by rnbguy** [jonhoo/msql-srv#13]
It only happens when I am stressing the server. This loop easily reproduces the exception on my Linux machine.

```
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

class Sql {
    public static void main(String[] args) throws SQLException {
        for(int i = 0; i < 1000; ++i) {
            Connection conn = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306",
                "",
                ""
            );
        }
    }
}
```

Replace `on_query()` method in `serve_one.rs` to accept JDBC connections. 
```
fn on_query(&mut self, sql: &str, results: QueryResultWriter<W>) -> io::Result<()> {
        println!("sqlquery {}", sql);
        use sqlparser::ast;
        use sqlparser::ast::Statement::Query;
        use sqlparser::dialect;
        use sqlparser::parser::Parser;
        let parsed_sql = Parser::parse_sql(&dialect::AnsiDialect {}, &sql)
            .or_else(|_| Parser::parse_sql(&dialect::GenericDialect {}, &sql))
            .or_else(|_| Parser::parse_sql(&dialect::MsSqlDialect {}, &sql))
            .or_else(|_| Parser::parse_sql(&dialect::MySqlDialect {}, &sql))
            .or_else(|_| Parser::parse_sql(&dialect::PostgreSqlDialect {}, &sql))
            .unwrap();
        match &parsed_sql[0] {
            Query(query) => {
                match &query.body {
                    ast::SetExpr::Select(ref s) => {
                        let mut col_writer = Vec::new();

                        for proj in &s.projection {
                            if let ast::SelectItem::ExprWithAlias { alias, .. } = proj {
                                let col = msql_srv::Column {
                                    table: "".into(),
                                    column: alias.value.clone(),
                                    coltype: msql_srv::ColumnType::MYSQL_TYPE_VAR_STRING,
                                    colflags: msql_srv::ColumnFlags::empty(),
                                };
                                col_writer.push(col);
                            }
                        }

                        let mut rw = results.start(&col_writer).unwrap();

                        for proj in &s.projection {
                            if let ast::SelectItem::ExprWithAlias { alias, .. } = proj {
                                // TODO : also handle STOCK_COUNT
                                let val = match alias.value.as_str() {
                                        "auto_increment_increment" => "1",
                                        "character_set_client" => "utf8",
                                        "character_set_connection" => "utf8",
                                        "character_set_results" => "utf8",
                                        "character_set_server" => "utf8mb4",
                                        "collation_server" => "utf8mb4_0900_ai_ci",
                                        "collation_connection" => "utf8_general_ci",
                                        "init_connect" => "",
                                        "interactive_timeout" => "28800",
                                        "license" => "GPL",
                                        "lower_case_table_names" => "0",
                                        "max_allowed_packet" => "67108864",
                                        "net_buffer_length" => "16384",
                                        "net_write_timeout" => "60",
                                        "sql_mode" => "ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION",
                                        "system_time_zone" => "UTC",
                                        "time_zone" => "SYSTEM",
                                        "wait_timeout" => "28800",
                                        "language" => "eng",
                                        "query_cache_size" => "",
                                        "query_cache_type" => "",
                                        "transaction_isolation" => "SERIALIZATION",
                                        e => unreachable!("NEW COLUMN {}", e),
                                    };
                                // println!("{} : {}", proj, val);
                                rw.write_col(val).unwrap();
                            }
                        }

                        rw.end_row().unwrap();

                        rw.finish()
                    }
                    _ => unimplemented!(),
                }
            }
            _ => results.completed(1, 0),
        }
    }
```

Now run them.

```
$ cargo run --release --example server_one &
$ javac Sql.java
$ java -cp .:./mysql-connector-java-5.1.48/mysql-connector-java-5.1.48.jar Sql
Exception in thread "main" java.sql.SQLException: ResultSet is from UPDATE. No Data.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.next(ResultSetImpl.java:6292)
	at com.mysql.jdbc.ConnectionImpl.loadServerVariables(ConnectionImpl.java:3768)
	at com.mysql.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:3196)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2233)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor3.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at Sql.main(Sql.java:8)
```

PS. I know there are other issues with JDBC driver already. I am trying to collect the bugs to fix them later. [5.1.48](https://downloads.mysql.com/archives/c-j) is the last version that does not complain about `CLIENT_SECURE_CONNECTION` (mit-pdos/noria-mysql#15).

**Comment by jonhoo** [comment]
Hi! I'm not quite sure what the issue you are reporting here is? What errors do you get from the `msql-srv` side of things? Could it be that the older Java version of the library is what is broken?

**Comment by rnbguy** [comment]
I am also not quite sure what is going on. I correctly write everything to the `result writer` and it works (almost) always. But sometimes JDBC complains saying `ResultSet is from UPDATE. No Data` - which means, the JDBC doesn't receive the data, that msql-srv is supposed to send.

I have opened the issue because this does not happen with a real MySQL server. But I agree, the older versions may be broken too.

**Comment by jonhoo** [comment]
Hmm, that's very weird indeed. Given that `msql-srv` doesn't actually share anything across connections, I'm _fairly_ sure this has to be some kind of concurrency issue on the Java side.
